# Generated by Django 3.2.6 on 2021-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='emailAuthenticated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
