# Generated by Django 3.2.6 on 2021-08-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='subscribed',
            field=models.IntegerField(default=0),
        ),
    ]
