# Generated by Django 3.2.6 on 2021-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_usereventinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shouldAttend',
            field=models.BooleanField(default=False),
        ),
    ]
